name: CI

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
          
    - name: Restore
      run: npm ci

    - name: Install rollup
      run: npm install -g rollup

    - name: Install jest
      run: npm install -g jest

    - name: Run Jest
      run: npm run test
      
    - name: Bundle
      run: rollup ./bound-element/main.js --file bundle.js --format cjs

    - name: Publish
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
