name: CI

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
          
    - name: Restore
      run: npm install
      
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.3

    - name: Install rollup
      run: npm install -g rollup
      
    - name: Bundle
      run: rollup ./base-web-component/main.js --file bundle.js --format iife

#    - name: Publish
#      run: npm publish --access public
#      env:
#        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
